# Generated by Django 5.2.1 on 2025-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPqrs', '0002_alter_usuario_usuempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='useFoto',
            field=models.ImageField(blank=True, null=True, upload_to='fotosusuario'),
        ),
    ]
