# Generated by Django 5.2.1 on 2025-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPqrs', '0003_usuario_usefoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usoTipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado')], max_length=20, null=True),
        ),
    ]
